apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-fabseit-net-dev
  namespace: halo
spec:
  secretName: local-fabseit-net-dev-tls
  issuerRef:
    name: cloudflare-clusterissuer-dev
    kind: ClusterIssuer
  commonName: "*.halo.fabseit.net"
  dnsNames:
    - "*.halo.fabseit.net"
