apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/orazefabian/homecluster-helm
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: halo
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
