---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config-pvc
  namespace: halo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi 
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-data-pvc
  namespace: halo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 60Gi 
  storageClassName: longhorn
