apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-config
  namespace: halo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn # Use Longhorn storage class


