apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: halo
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP # Internal service for Paperless communication only
