apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-upload-pvc
  namespace: halo
  labels:
    recurring-job-group.longhorn.io/default: "enabled"
    recurring-job.longhorn.io/main-backup: "enabled"
    recurring-job.longhorn.io/s3-monthly-backup: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-cache-pvc
  namespace: halo
  labels:
    recurring-job-group.longhorn.io/default: "enabled"
    recurring-job.longhorn.io/main-backup: "enabled"
    recurring-job.longhorn.io/s3-monthly-backup: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
