apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headplane-data
  namespace: halo
  labels:
    recurring-job-group.longhorn.io/default: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
