apiVersion: v1
kind: Namespace
metadata:
  name: velero
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: velero
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: velero
      app.kubernetes.io/instance: velero
  template:
    metadata:
      labels:
        app.kubernetes.io/name: velero
        app.kubernetes.io/instance: velero
    spec:
      serviceAccountName: velero
      containers:
        - name: velero
          image: velero/velero:v1.12.0
          args:
            - server
            - --restic-timeout=2h
            - --default-volumes-to-restic
            - --upload-progress-timeout=60m
          env:
            - name: VELERO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: VELERO_SCRATCH_DIR
              value: /scratch
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: velero-encryption
                  key: encryption-key
            - name: TZ
              value: "Europe/Berlin"
          volumeMounts:
            - name: plugins
              mountPath: /plugins
            - name: scratch
              mountPath: /scratch
            - name: creds
              mountPath: /credentials
            - name: cloud-credentials
              mountPath: /credentials-velero
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
      initContainers:
        - name: initialize-restic-plugin
          image: velero/velero-plugin-for-aws:v1.8.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: plugins
              mountPath: /target
          command:
            - cp
            - /velero-plugin-for-aws
            - /target/velero-plugin-for-aws
        - name: initialize-sftp-plugin
          image: itix/velero-plugin-for-sftp:v0.3.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: plugins
              mountPath: /target
          command:
            - cp
            - /velero-plugin-for-sftp
            - /target/velero-plugin-for-sftp
      volumes:
        - name: plugins
          emptyDir: {}
        - name: scratch
          emptyDir: {}
        - name: creds
          secret:
            secretName: sftp-credentials
        - name: cloud-credentials
          secret:
            secretName: sftp-credentials
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: restic
  namespace: velero
  labels:
    app.kubernetes.io/name: restic
    app.kubernetes.io/instance: velero
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: restic
      app.kubernetes.io/instance: velero
  template:
    metadata:
      labels:
        app.kubernetes.io/name: restic
        app.kubernetes.io/instance: velero
    spec:
      serviceAccountName: velero
      securityContext:
        runAsUser: 0
      containers:
        - name: restic
          image: velero/velero:v1.12.0
          command:
            - /velero
          args:
            - restic
            - server
          env:
            - name: VELERO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VELERO_SCRATCH_DIR
              value: /scratch
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: velero-encryption
                  key: encryption-key
            - name: TZ
              value: "Europe/Berlin"
          volumeMounts:
            - name: host-pods
              mountPath: /host_pods
              mountPropagation: HostToContainer
            - name: scratch
              mountPath: /scratch
            - name: creds
              mountPath: /credentials
            - name: cloud-credentials
              mountPath: /credentials-velero
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
      volumes:
        - name: host-pods
          hostPath:
            path: /var/lib/kubelet/pods
        - name: scratch
          emptyDir: {}
        - name: creds
          secret:
            secretName: sftp-credentials
        - name: cloud-credentials
          secret:
            secretName: sftp-credentials
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero
  namespace: velero
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero
subjects:
  - kind: ServiceAccount
    name: velero
    namespace: velero
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io