apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-manifests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/orazefabian/homecluster-helm
    targetRevision: HEAD
    path: ./infrastructure/monitoring/manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: false
