apiVersion: v1
kind: ConfigMap
metadata:
  name: samba-config
  namespace: halo
data:
  config.yml: |
    auth:
      - user: fabian
        group: cevh
        uid: 1000
        gid: 1000
        password: ${FABIAN_PW}
      - user: benjamin
        group: cevh
        uid: 1001
        gid: 1000
        password: ${BENJAMIN_PW}
      - user: damian
        group: cevh
        uid: 1002
        gid: 1000
        password: ${DAMIAN_PW}
      - user: silvia
        group: cevh
        uid: 1003
        gid: 1000
        password: ${SILVIA_PW}

    global:
      - "force group = cevh"
      - "hosts allow = 0.0.0.0/0"

    share:
      - name: fabian
        path: /mnt/data/fabian
        browsable: yes
        readonly: no
        guestok: no
        validusers: fabian
      - name: benjamin
        path: /mnt/data/benjamin
        browsable: yes
        readonly: no
        guestok: no
        validusers: benjamin
      - name: damian
        path: /mnt/data/damian
        browsable: yes
        readonly: no
        guestok: no
        validusers: damian
      - name: silvia
        path: /mnt/data/sivlia
        browsable: yes
        readonly: no
        guestok: no
        validusers: silvia
      - name: home
        path: /mnt/data/home
        browsable: yes
        readonly: no
        guestok: no
        validusers: fabian,benjamin,damian,sivlia
