apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: halo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: pihole
          image: pihole/pihole:2024.06.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "250m" # Request at least a fourth of a CPU core.
              memory: "256Mi"
            limits:
              cpu: "2" # Allow up to 2 full CPU cores.
              memory: "512Mi"
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            - containerPort: 80
              protocol: TCP
          env:
            - name: TZ
              value: "Europe/Berlin"
            - name: DNSMASQ_USER
              value: "pihole"
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-secret
                  key: WEBPASSWORD
            - name: PIHOLE_DNS_
              value: "9.9.9.9;1.1.1.1"
          volumeMounts:
            - mountPath: /etc/dnsmasq.d
              name: dnsmasq-config-volume
            - mountPath: /etc/pihole
              name: pihole-config-volume
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      volumes:
        - name: dnsmasq-config-volume
          persistentVolumeClaim:
            claimName: pihole-dnsmasq # Shared PVC for both volumes.
        - name: pihole-config-volume
          persistentVolumeClaim:
            claimName: pihole-config # Shared PVC for both volumes.
