apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-admin-reroute
  namespace: halo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /admin
spec:
  ingressClassName: nginx # Specify the Traefik ingress class explicitly
  rules:
    - host: pihole.halo.fabseit.net # Match the host
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: pihole 
                port:
                  number: 80 
  tls:
    - hosts:
        - pihole.halo.fabseit.net # TLS will apply to this host
      secretName: local-fabseit-net-prod-tls # Reference to the TLS secret

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole
  namespace: halo
spec:
  ingressClassName: nginx # Specify the Traefik ingress class explicitly
  rules:
    - host: pihole.halo.fabseit.net # Match the host
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: pihole 
                port:
                  number: 80 
  tls:
    - hosts:
        - pihole.halo.fabseit.net # TLS will apply to this host
      secretName: local-fabseit-net-prod-tls # Reference to the TLS secret
