apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config
  namespace: halo
  labels:
    recurring-job-group.longhorn.io/default: "enabled"
    recurring-job.longhorn.io/random-volumes: "enabled"
    recurring-job.longhorn.io/s3-monthly-backup: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: longhorn # Use Longhorn storage class

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq
  namespace: halo
  labels:
    recurring-job-group.longhorn.io/default: "enabled"
    recurring-job.longhorn.io/random-volumes: "enabled"
    recurring-job.longhorn.io/s3-monthly-backup: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn # Use Longhorn storage class
