apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: halo
spec:
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      containers:
      - name: paperless
        image: ghcr.io/paperless-ngx/paperless-ngx:2.16.3
        ports:
        - containerPort: 8000
        env:
        # PostgreSQL Configuration
        - name: PAPERLESS_DB_HOST
          value: "postgres-service"
        - name: PAPERLESS_DB_PORT
          value: "5432"
        - name: PAPERLESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: PAPERLESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: PAPERLESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        
        # Redis Configuration
        - name: PAPERLESS_REDIS
          value: "redis://redis-service:6379"
        
        # Core Paperless Configuration
        - name: PAPERLESS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: paperless-secret
              key: PAPERLESS_SECRET_KEY
        - name: PAPERLESS_URL
          valueFrom:
            secretKeyRef:
              name: paperless-secret
              key: PAPERLESS_URL
        
        # Storage Configuration
        volumeMounts:
        - name: paperless-storage
          mountPath: /usr/src/paperless/data
          subPath: data
        - name: paperless-storage
          mountPath: /usr/src/paperless/media
          subPath: media
      volumes:
      - name: paperless-storage
        persistentVolumeClaim:
          claimName: paperless-pvc
