apiVersion: v1
kind: Service
metadata:
  name: dober-dan-piper
  namespace: halo
spec:
  type: ClusterIP
  selector:
    app: dober-dan-piper
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
