---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-fabseit-net-prod
  namespace: longhorn-system
spec:
  secretName: longhorn-fabseit-net-prod-tls
  issuerRef:
    name: cloudflare-clusterissuer-prod
    kind: ClusterIssuer
  commonName: "*.halo.fabseit.net"
  dnsNames:
    - "halo.fabseit.net"
    - "*.halo.fabseit.net"

