apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-fabseit-net-dev
  namespace: longhorn-system
spec:
  secretName: longhorn-fabseit-net-dev-tls
  issuerRef:
    name: cloudflare-clusterissuer-dev
    kind: ClusterIssuer
  commonName: "*.halo.fabseit.net"
  dnsNames:
    - "halo.fabseit.net"
    - "*.halo.fabseit.net"

