apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-n8n
  namespace: halo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-n8n
  template:
    metadata:
      labels:
        app: postgres-n8n
    spec:
      containers:
        - name: postgres-n8n
          image: postgres:15-alpine
          envFrom:
          - secretRef:
              name: n8n-db-secret
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
              subPath: n8n
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: pg-n8n-data

