apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-n8n-data
  namespace: halo
  labels:
    recurring-job-group.longhorn.io/default: "enabled"
    recurring-job.longhorn.io/random-volumes: "enabled"
    recurring-job.longhorn.io/s3-monthly-backup: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi

