apiVersion: v1
kind: Service
metadata:
  name: postgres-n8n
  namespace: halo
spec:
  type: ClusterIP
  selector:
    app: postgres-n8n
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP

